#!/bin/bash

while read name; do
if [[ -n $name ]]; then
cat <<EOF
$name.cc: ../../$name.js
	xxd -i ../../$name.js | sed 's/_*${name}_js/node_script/g' > $name.cc

$name: bench.dtb $name.cc
	NODE_BENCH=1 NODE_SCRIPT="$name" \$(MAKE) -C Release

.PHONY: ${name}dbg
${name}dbg: bench.dtb $name.cc
	NODE_BENCH=1 NODE_SCRIPT="$name" \$(MAKE) -C Debug
EOF

clean="$clean\n\tNODE_BENCH=1 NODE_SCRIPT=\"$name\" \$(MAKE) -C Release clean\n\tNODE_BENCH=1 NODE_SCRIPT=\"$name\" \$(MAKE) -C Debug clean"

fi
done
echo -e "clean: $clean"


